# Generated by Django 4.0.2 on 2023-01-25 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_kadeqoriyalar_postlar_muellifler'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Kadeqoriyalar',
        ),
        migrations.RemoveField(
            model_name='postlar',
            name='author',
        ),
        migrations.RemoveField(
            model_name='postlar',
            name='categories',
        ),
        migrations.DeleteModel(
            name='Muellifler',
        ),
        migrations.DeleteModel(
            name='Postlar',
        ),
    ]
