# Generated by Django 4.0.2 on 2023-01-25 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_exam_delete_kadeqoriyalar_remove_postlar_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='Fakulte',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='exam',
            name='Ixtisas',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='exam',
            name='Universitet',
            field=models.CharField(default='', max_length=20),
        ),
    ]
